--------------------------------------------------------------------------------
-- Clink argmatcher for cp (GNU coreutils)
--

clink.argmatcher("cp")
:adddescriptions({
    ["-r"] = { "递归复制目录" },
    ["-R"] = { "递归复制目录" },
    ["--recursive"] = { "递归复制目录" },
    ["-f"] = { "如果无法打开现有的目标文件，则删除它并重试" },
    ["--force"] = { "如果无法打开现有的目标文件，则删除它并重试" },
    ["-i"] = { "覆盖前提示" },
    ["--interactive"] = { "覆盖前提示" },
    ["-n"] = { "不覆盖现有文件" },
    ["--no-clobber"] = { "不覆盖现有文件" },
    ["-v"] = { "说明正在执行的操作" },
    ["--verbose"] = { "说明正在执行的操作" },
    ["-u"] = { "仅在源文件比目标文件更新时才复制" },
    ["--update"] = { "仅在源文件比目标文件更新时才复制" },
    ["-p"] = { "保留文件属性（模式、所有权、时间戳）" },
    ["--preserve"] = { "保留文件属性（模式、所有权、时间戳）" },
    ["-a"] = { "归档模式；等同于 -dR --preserve=all" },
    ["--archive"] = { "归档模式；等同于 -dR --preserve=all" },
    ["-l"] = { "创建硬链接而非复制" },
    ["--link"] = { "创建硬链接而非复制" },
    ["-s"] = { "创建符号链接而非复制" },
    ["--symbolic-link"] = { "创建符号链接而非复制" },
    ["-T"] = { "将目标视为普通文件" },
    ["--no-target-directory"] = { "将目标视为普通文件" },
    ["-t"] = { " arg", "将所有源文件复制到 DIRECTORY" },
    ["--target-directory"] = { " arg", "将所有源文件复制到 DIRECTORY" },
    ["-b"] = { "备份每个现有的目标文件" },
    ["--backup"] = { "备份每个现有的目标文件" },
    ["-d"] = { "等同于 --no-dereference --preserve=links" },
    ["-P"] = { "绝不跟随符号链接" },
    ["--no-dereference"] = { "绝不跟随符号链接" },
    ["--parents"] = { "在 DIRECTORY 下使用完整源文件名" },
    ["--strip-trailing-slashes"] = { "从每个源参数中移除尾随斜杠" },
    ["-H"] = { "解引用命令行中列出的符号链接" },
    ["-L"] = { "始终跟随源文件中的符号链接" },
    ["--dereference"] = { "始终跟随源文件中的符号链接" },
    ["-S"] = { " suffix", "覆盖默认的备份后缀" },
    ["--suffix"] = { " suffix", "覆盖默认的备份后缀" },
    ["-x"] = { "仅在本文件系统中操作" },
    ["--one-file-system"] = { "仅在本文件系统中操作" },
    ["-Z"] = { "设置目标文件的 SELinux 安全上下文" },
    ["--context"] = { " ctx", "类似 -Z，或指定 CTX 设置安全上下文" },
    ["--attributes-only"] = { "仅复制属性，不复制数据" },
    ["--copy-contents"] = { "递归复制特殊文件的内容" },
    ["--no-preserve"] = { " attr-list", "不保留指定属性" },
    ["--reflink"] = { " when", "控制克隆/写时复制副本：auto, always, never" },
    ["--remove-destination"] = { "打开前删除每个已存在的目标文件" },
    ["--sparse"] = { " when", "控制稀疏文件的创建：auto, always, never" },
    ["--help"] = { "显示帮助并退出" },
    ["--version"] = { "输出版本信息并退出" },
})
:addflags({
    "-r", "-R", "--recursive",
    "-f", "--force",
    "-i", "--interactive",
    "-n", "--no-clobber",
    "-v", "--verbose",
    "-u", "--update",
    "-p", "--preserve",
    "-a", "--archive",
    "-l", "--link",
    "-s", "--symbolic-link",
    "-T", "--no-target-directory",
    "-t"..(clink.argmatcher():addarg(clink.dirmatches)),
    "--target-directory="..(clink.argmatcher():addarg(clink.dirmatches)),
    "-b", "--backup",
    "-d",
    "-P", "--no-dereference",
    "--parents",
    "--strip-trailing-slashes",
    "-H",
    "-L", "--dereference",
    "-S"..(clink.argmatcher():addarg({fromhistory=true})),
    "--suffix="..(clink.argmatcher():addarg({fromhistory=true})),
    "-x", "--one-file-system",
    "-Z",
    "--context="..(clink.argmatcher():addarg({fromhistory=true})),
    "--attributes-only",
    "--copy-contents",
    "--no-preserve="..(clink.argmatcher():addarg({fromhistory=true})),
    "--reflink="..(clink.argmatcher():addarg({"auto", "always", "never"})),
    "--remove-destination",
    "--sparse="..(clink.argmatcher():addarg({"auto", "always", "never"})),
    "--help", "--version",
})
