-- luacheck: no max line length
--------------------------------------------------------------------------------
-- gcc.lua — MinGW GCC / G++ 编译器

local freeform = clink.argmatcher():addarg({fromhistory=true})
local file = clink.argmatcher():addarg(clink.filematches)

local common_flags = {
    "-c",
    "-S",
    "-E",
    "-o"..file,
    "-g",
    "-g3",
    "-O0",
    "-O1",
    "-O2",
    "-O3",
    "-Os",
    "-Og",
    "-Wall",
    "-Wextra",
    "-Werror",
    "-w",
    "-pedantic",
    "-std"..freeform,
    "-D"..freeform,
    "-U"..freeform,
    "-I"..clink.argmatcher():addarg(clink.dirmatches),
    "-L"..clink.argmatcher():addarg(clink.dirmatches),
    "-l"..freeform,
    "-pthread",
    "-fPIC",
    "-fPIE",
    "-fno-strict-aliasing",
    "-fstack-protector",
    "-fstack-protector-strong",
    "-fsanitize"..freeform,
    "-fopenmp",
    "-MMD",
    "-MF"..file,
    "-m32",
    "-m64",
    "-march"..freeform,
    "-mtune"..freeform,
    "-static",
    "-shared",
    "-s",
    "-x"..freeform,
    "-v",
    "--version",
    "-###",
    "-Wl,"..freeform,
    "-MM",
    "-M",
}

clink.argmatcher("gcc")
:addflags(common_flags)
:addarg(file)
:adddescriptions({
    ["-c"] = { "只编译不链接（生成 .o 文件）" },
    ["-S"] = { "只编译生成汇编文件（.s）" },
    ["-E"] = { "只做预处理，输出到标准输出" },
    ["-o"] = { " file", "指定输出文件" },
    ["-g"] = { "生成调试信息" },
    ["-g3"] = { "生成最详细的调试信息" },
    ["-O0"] = { "不优化" },
    ["-O1"] = { "优化（速度与体积平衡）" },
    ["-O2"] = { "推荐优化级别" },
    ["-O3"] = { "激进优化" },
    ["-Os"] = { "优化体积" },
    ["-Og"] = { "为调试优化的优化" },
    ["-Wall"] = { "启用所有常用警告" },
    ["-Wextra"] = { "启用额外警告" },
    ["-Werror"] = { "将警告视为错误" },
    ["-w"] = { "禁用所有警告" },
    ["-pedantic"] = { "严格遵循标准（拒绝扩展）" },
    ["-std"] = { " standard", "语言标准：c11 / c17 / c++17 / c++20 等" },
    ["-D"] = { " macro", "定义宏，如 -DNDEBUG" },
    ["-U"] = { " macro", "取消定义宏" },
    ["-I"] = { " dir", "添加头文件搜索目录" },
    ["-L"] = { " dir", "添加库搜索目录" },
    ["-l"] = { " lib", "链接库，如 -lm、-lstdc++" },
    ["-pthread"] = { "启用 POSIX 线程支持" },
    ["-fPIC"] = { "生成位置无关代码（共享库）" },
    ["-fPIE"] = { "生成位置无关可执行文件" },
    ["-fstack-protector"] = { "启用栈保护" },
    ["-fsanitize"] = { " sanitizer", "启用消毒器：address / undefined / thread" },
    ["-fopenmp"] = { "启用 OpenMP 并行" },
    ["-MMD"] = { "生成头文件依赖（不含系统头）" },
    ["-MF"] = { " file", "依赖输出文件" },
    ["-m32"] = { "生成 32 位代码" },
    ["-m64"] = { "生成 64 位代码" },
    ["-march"] = { " cpu", "指定目标 CPU，如 native / x86-64" },
    ["-static"] = { "静态链接" },
    ["-shared"] = { "生成共享库（.dll）" },
    ["-s"] = { "去除符号表（strip）" },
    ["-x"] = { " lang", "指定输入语言：c / c++ / assembler" },
    ["-v"] = { "显示编译过程详细输出" },
    ["--version"] = { "显示版本" },
    ["-Wl,"] = { " option", "传递选项给链接器" },
    ["-MM"] = { "输出依赖（不含系统头，无目标）" },
    ["-M"] = { "输出依赖（含系统头，无目标）" },
})

clink.argmatcher("g++")
:addflags(common_flags)
:addarg(file)
:adddescriptions({
    ["-c"] = { "只编译不链接（生成 .o 文件）" },
    ["-S"] = { "只编译生成汇编文件（.s）" },
    ["-E"] = { "只做预处理，输出到标准输出" },
    ["-o"] = { " file", "指定输出文件" },
    ["-g"] = { "生成调试信息" },
    ["-O0"] = { "不优化" },
    ["-O1"] = { "优化（速度与体积平衡）" },
    ["-O2"] = { "推荐优化级别" },
    ["-O3"] = { "激进优化" },
    ["-Wall"] = { "启用所有常用警告" },
    ["-Wextra"] = { "启用额外警告" },
    ["-Werror"] = { "将警告视为错误" },
    ["-std"] = { " standard", "语言标准：c++11 / c++14 / c++17 / c++20 / c++23" },
    ["-D"] = { " macro", "定义宏" },
    ["-I"] = { " dir", "添加头文件搜索目录" },
    ["-L"] = { " dir", "添加库搜索目录" },
    ["-l"] = { " lib", "链接库" },
    ["-pthread"] = { "启用 POSIX 线程支持" },
    ["-fPIC"] = { "生成位置无关代码（共享库）" },
    ["-fopenmp"] = { "启用 OpenMP 并行" },
    ["-m64"] = { "生成 64 位代码" },
    ["-m32"] = { "生成 32 位代码" },
    ["-static"] = { "静态链接" },
    ["-shared"] = { "生成共享库（.dll）" },
    ["-s"] = { "去除符号表（strip）" },
    ["-v"] = { "显示编译过程详细输出" },
    ["--version"] = { "显示版本" },
})
