--------------------------------------------------------------------------------
-- Clink argmatcher for ls (GNU coreutils)
--

local sort_matcher = clink.argmatcher():addarg({"none", "size", "time", "version", "extension"})
local time_matcher = clink.argmatcher():addarg({"atime", "access", "use", "ctime", "status", "birth", "mtime", "modification"})
local time_style_matcher = clink.argmatcher():addarg({"full-iso", "long-iso", "iso", "locale", "+FORMAT"})
local format_matcher = clink.argmatcher():addarg({"across", "commas", "horizontal", "long", "single-column", "verbose", "vertical"})
local indicator_matcher = clink.argmatcher():addarg({"none", "slash", "file-type", "classify"})
local quoting_matcher = clink.argmatcher():addarg({"literal", "shell", "shell-always", "c", "escape", "locale", "clocale"})
local when_matcher = clink.argmatcher():addarg({"always", "auto", "never"})

clink.argmatcher("ls")
:addarg(clink.dirmatches)
:adddescriptions({
    ["-a"] = { "不忽略以 . 开头的条目" },
    ["--all"] = { "不忽略以 . 开头的条目" },
    ["-A"] = { "不列出隐含的 . 和 .." },
    ["--almost-all"] = { "不列出隐含的 . 和 .." },
    ["-l"] = { "使用长列表格式" },
    ["-h"] = { "以人类可读的格式打印大小（例如 1K 234M 2G）" },
    ["--human-readable"] = { "以人类可读的格式打印大小（例如 1K 234M 2G）" },
    ["-r"] = { "排序时反转顺序" },
    ["--reverse"] = { "排序时反转顺序" },
    ["-t"] = { "按修改时间排序，最新优先" },
    ["-S"] = { "按文件大小排序，最大优先" },
    ["--sort=size"] = { "按文件大小排序，最大优先" },
    ["-R"] = { "递归列出子目录" },
    ["--recursive"] = { "递归列出子目录" },
    ["-1"] = { "每行列出一个文件" },
    ["-F"] = { "向条目追加指示符（*/=>@| 之一）" },
    ["--classify"] = { "向条目追加指示符（*/=>@| 之一）" },
    ["-d"] = { "列出目录本身，而非其内容" },
    ["--directory"] = { "列出目录本身，而非其内容" },
    ["-i"] = { "打印每个文件的 inode 号" },
    ["--inode"] = { "打印每个文件的 inode 号" },
    ["-L"] = { "跟随符号链接，显示目标文件信息" },
    ["--dereference"] = { "跟随符号链接，显示目标文件信息" },
    ["-p"] = { "向目录追加 / 指示符" },
    ["--indicator-style=slash"] = { "向目录追加 / 指示符" },
    ["-s"] = { "打印每个文件的分配大小（以块为单位）" },
    ["--size"] = { "打印每个文件的分配大小（以块为单位）" },
    ["-X"] = { "按条目扩展名的字母顺序排序" },
    ["--sort=extension"] = { "按条目扩展名的字母顺序排序" },
    ["-U"] = { "不排序；按目录顺序列出条目" },
    ["--sort=none"] = { "不排序；按目录顺序列出条目" },
    ["-v"] = { "对文本中的版本号进行自然排序" },
    ["--sort=version"] = { "对文本中的版本号进行自然排序" },
    ["-c"] = { "与 -lt 一起使用：按 ctime 排序并显示" },
    ["-u"] = { "与 -lt 一起使用：按访问时间排序并显示" },
    ["--color"] = { " arg", "着色输出：auto, always, never" },
    ["--help"] = { "显示帮助并退出" },
    ["--version"] = { "输出版本信息并退出" },
    -- 新增选项
    ["--author"] = { "与 -l 一起使用时，打印每个文件的作者" },
    ["-b"] = { "用 C 风格转义打印非图形字符" },
    ["--escape"] = { "用 C 风格转义打印非图形字符" },
    ["--block-size"] = { " size", "与 -l 一起使用时，按 SIZE 缩放打印大小" },
    ["-B"] = { "不列出以 ~ 结尾的隐含条目" },
    ["--ignore-backups"] = { "不列出以 ~ 结尾的隐含条目" },
    ["-C"] = { "按列列出条目（默认方式）" },
    ["-D"] = { "生成适合 Emacs dired 模式的输出" },
    ["--dired"] = { "生成适合 Emacs dired 模式的输出" },
    ["-f"] = { "不排序，启用 -aU，禁用 -ls --color" },
    ["--file-type"] = { "与 --classify 类似，但不追加 *" },
    ["--format"] = { " word", "指定输出格式：across, commas, horizontal, long, single-column, verbose, vertical" },
    ["--full-time"] = { "类似 -l --time-style=full-iso" },
    ["-g"] = { "类似 -l，但不列出所有者" },
    ["--group-directories-first"] = { "目录排在文件之前" },
    ["-G"] = { "长列表中不打印组名" },
    ["--no-group"] = { "长列表中不打印组名" },
    ["-H"] = { "解引用命令行中列出的符号链接" },
    ["--dereference-command-line"] = { "解引用命令行中列出的符号链接" },
    ["--dereference-command-line-symlink-to-dir"] = { "仅解引用命令行中指向目录的符号链接" },
    ["--hide"] = { " pattern", "不列出匹配 shell PATTERN 的隐含条目" },
    ["--hyperlink"] = { " when", "为文件名添加超链接：always, auto, never" },
    ["--indicator-style"] = { " word", "按指定样式追加指示符：none, slash, file-type, classify" },
    ["-I"] = { " pattern", "不列出匹配 shell PATTERN 的隐含条目" },
    ["--ignore"] = { " pattern", "不列出匹配 shell PATTERN 的隐含条目" },
    ["-k"] = { "磁盘使用量默认使用 1024 字节块" },
    ["--kibibytes"] = { "磁盘使用量默认使用 1024 字节块" },
    ["-m"] = { "用逗号分隔的条目列表填满宽度" },
    ["-n"] = { "类似 -l，但列出数字 UID 和 GID" },
    ["--numeric-uid-gid"] = { "类似 -l，但列出数字 UID 和 GID" },
    ["-N"] = { "打印条目名称而不加引号" },
    ["--literal"] = { "打印条目名称而不加引号" },
    ["-o"] = { "类似 -l，但不列出组信息" },
    ["-q"] = { "用 ? 代替非图形字符" },
    ["--hide-control-chars"] = { "用 ? 代替非图形字符" },
    ["--show-control-chars"] = { "按原样显示非图形字符" },
    ["-Q"] = { "用双引号括起条目名称" },
    ["--quote-name"] = { "用双引号括起条目名称" },
    ["--quoting-style"] = { " word", "为条目名称使用指定引用样式" },
    ["--si"] = { "类似 -h，但使用 1000 而非 1024 的幂" },
    ["--sort"] = { " word", "按 WORD 排序：none, size, time, version, extension" },
    ["--time"] = { " word", "更改默认使用的修改时间：atime, ctime, birth, mtime" },
    ["--time-style"] = { " style", "与 -l 一起使用的时间/日期格式" },
    ["-T"] = { " cols", "每 COLS 列设置制表位" },
    ["--tabsize"] = { " cols", "每 COLS 列设置制表位" },
    ["-w"] = { " cols", "将输出宽度设置为 COLS，0 表示无限制" },
    ["--width"] = { " cols", "将输出宽度设置为 COLS，0 表示无限制" },
    ["-x"] = { "按行而非按列列出条目" },
    ["-Z"] = { "打印每个文件的安全上下文" },
    ["--context"] = { "打印每个文件的安全上下文" },
    ["--append-exe"] = { "需要时追加 .exe（cygwin 特定）" },
})
:addflags({
    "-a", "--all",
    "-A", "--almost-all",
    "-l",
    "-h", "--human-readable",
    "-r", "--reverse",
    "-t",
    "-S", "--sort=size",
    "-R", "--recursive",
    "-1",
    "-F", "--classify",
    "-d", "--directory",
    "-i", "--inode",
    "-L", "--dereference",
    "-p", "--indicator-style=slash",
    "-s", "--size",
    "-X", "--sort=extension",
    "-U", "--sort=none",
    "-v", "--sort=version",
    "-c", "-u",
    "--color="..when_matcher,
    "--help", "--version",
    -- 新增选项
    "--author",
    "-b", "--escape",
    "--block-size="..(clink.argmatcher():addarg({fromhistory=true})),
    "-B", "--ignore-backups",
    "-C",
    "-D", "--dired",
    "-f",
    "--file-type",
    "--format="..format_matcher,
    "--full-time",
    "-g",
    "--group-directories-first",
    "-G", "--no-group",
    "-H", "--dereference-command-line",
    "--dereference-command-line-symlink-to-dir",
    "--hide="..(clink.argmatcher():addarg({fromhistory=true})),
    "--hyperlink="..when_matcher,
    "--indicator-style="..indicator_matcher,
    "-I"..(clink.argmatcher():addarg({fromhistory=true})),
    "--ignore="..(clink.argmatcher():addarg({fromhistory=true})),
    "-k", "--kibibytes",
    "-m",
    "-n", "--numeric-uid-gid",
    "-N", "--literal",
    "-o",
    "-q", "--hide-control-chars",
    "--show-control-chars",
    "-Q", "--quote-name",
    "--quoting-style="..quoting_matcher,
    "--si",
    "--sort="..sort_matcher,
    "--time="..time_matcher,
    "--time-style="..time_style_matcher,
    "-T"..(clink.argmatcher():addarg({fromhistory=true})),
    "--tabsize="..(clink.argmatcher():addarg({fromhistory=true})),
    "-w"..(clink.argmatcher():addarg({fromhistory=true})),
    "--width="..(clink.argmatcher():addarg({fromhistory=true})),
    "-x",
    "-Z", "--context",
    "--append-exe",
})
