-- luacheck: no max line length
--------------------------------------------------------------------------------
-- powercfg.lua — 电源配置

local freeform = clink.argmatcher():addarg({fromhistory=true})

clink.argmatcher("powercfg")
:addflags({
    "/list",
    "/aliases",
    "/getactivescheme",
    "/setactive"..freeform,
    "/query"..freeform,
    "/change"..freeform,
    "/setacvalueindex"..freeform,
    "/setdcvalueindex"..freeform,
    "/hibernate"..freeform,
    "/energy",
    "/batteryreport",
    "/sleepstudy",
    "/systempowerreport",
    "/availablesleepstates",
    "/waketimers",
    "/requests",
    "/devicequery"..freeform,
    "/devicedisablewake"..freeform,
    "/deviceenablewake"..freeform,
    "/lastwake",
    "/restoredefaultschemes",
    "/import"..freeform,
    "/export"..freeform,
    "/duplicatescheme"..freeform,
    "/delete"..freeform,
    "/changename"..freeform,
    "/srumutil",
    "/?",
})
:adddescriptions({
    ["/list"] = { "列出所有电源方案（GUID）" },
    ["/aliases"] = { "显示电源方案的别名" },
    ["/getactivescheme"] = { "显示当前活动电源方案" },
    ["/setactive"] = { " scheme-guid", "激活指定电源方案" },
    ["/query"] = { " scheme", "显示电源方案详细信息" },
    ["/change"] = { "设置当前方案的属性，如 /change monitor-timeout-ac 5" },
    ["/setacvalueindex"] = { "设置交流电（插电）下的电源设置值" },
    ["/setdcvalueindex"] = { "设置直流电（电池）下的电源设置值" },
    ["/hibernate"] = { " on/off", "启用/禁用休眠：/hibernate on|off" },
    ["/energy"] = { "生成系统电源效率诊断报告（energy-report.html）" },
    ["/batteryreport"] = { "生成电池使用报告（battery-report.html）" },
    ["/sleepstudy"] = { "生成睡眠研究诊断报告" },
    ["/systempowerreport"] = { "生成系统电源报告" },
    ["/availablesleepstates"] = { "报告本机可用的睡眠状态" },
    ["/waketimers"] = { "列出活动唤醒计时器" },
    ["/requests"] = { "列出阻止睡眠的电源请求" },
    ["/devicequery"] = { " query", "查询设备：wake_armed / wake_programmable 等" },
    ["/devicedisablewake"] = { " device", "禁止设备唤醒计算机" },
    ["/deviceenablewake"] = { " device", "允许设备唤醒计算机" },
    ["/lastwake"] = { "报告上次唤醒计算机的事件" },
    ["/restoredefaultschemes"] = { "恢复默认电源方案" },
    ["/import"] = { " file", "从文件导入电源方案" },
    ["/export"] = { " file", "导出电源方案到文件" },
    ["/duplicatescheme"] = { " scheme", "复制电源方案" },
    ["/delete"] = { " scheme", "删除电源方案" },
    ["/changename"] = { "重命名电源方案" },
    ["/srumutil"] = { "转储系统资源使用数据" },
    ["/?"] = { "显示帮助" },
})
