-- luacheck: no max line length
--------------------------------------------------------------------------------
-- tar.lua — GNU tar

local freeform = clink.argmatcher():addarg({fromhistory=true})
local file = clink.argmatcher():addarg(clink.filematches)

clink.argmatcher("tar")
:addflags({
    "-A", "--catenate", "--concatenate",
    "-c", "--create",
    "--delete",
    "-d", "--diff", "--compare",
    "-r", "--append",
    "--test-label",
    "-t", "--list",
    "-u", "--update",
    "-x", "--extract", "--get",
    "-f"..file,
    "--file="..file,
    "-v", "--verbose",
    "-z", "--gzip", "--gunzip",
    "-j", "--bzip2",
    "-J", "--xz",
    "--zstd",
    "-a", "--auto-compress",
    "-k", "--keep-old-files",
    "--keep-newer-files",
    "--overwrite",
    "--remove-files",
    "--skip-old-files",
    "-U", "--unlink-first",
    "-O", "--to-stdout",
    "-C"..clink.argmatcher():addarg(clink.dirmatches),
    "--directory="..clink.argmatcher():addarg(clink.dirmatches),
    "--exclude="..freeform,
    "-X"..file,
    "--exclude-from="..file,
    "-T"..file,
    "--files-from="..file,
    "-p", "--preserve-permissions",
    "--same-permissions",
    "-h", "--dereference",
    "--hard-dereference",
    "--strip-components="..freeform,
    "--one-top-level",
    "-S", "--sparse",
    "--ignore-failed-read",
    "--ignore-command-error",
    "-g"..freeform,
    "--listed-incremental="..freeform,
    "-G", "--incremental",
    "--checkpoint",
    "--checkpoint-action="..freeform,
    "-w", "--interactive",
    "--warning="..freeform,
    "--wildcards",
    "--no-wildcards",
    "--ignore-case",
    "--no-ignore-case",
    "--null",
    "--verbatim-files-from",
    "--version",
    "-W", "--verify",
    "--help",
})
:addarg(freeform)
:adddescriptions({
    ["-c"] = { "创建新归档" },
    ["--create"] = { "创建新归档" },
    ["-x"] = { "从归档解压" },
    ["--extract"] = { "从归档解压" },
    ["-t"] = { "列出归档内容" },
    ["--list"] = { "列出归档内容" },
    ["-r"] = { "追加文件到归档末尾" },
    ["-u"] = { "仅追加比归档中更新的文件" },
    ["-A"] = { "追加 tar 文件到归档" },
    ["-d"] = { "比较归档与文件系统的差异" },
    ["--delete"] = { "从归档中删除（磁带除外）" },
    ["-f"] = { " archive", "指定归档文件" },
    ["-v"] = { "详细输出" },
    ["-z"] = { "通过 gzip 压缩/解压" },
    ["-j"] = { "通过 bzip2 压缩/解压" },
    ["-J"] = { "通过 xz 压缩/解压" },
    ["--zstd"] = { "通过 zstd 压缩/解压" },
    ["-a"] = { "根据后缀自动选择压缩方式" },
    ["-k"] = { "解压时不覆盖已存在文件" },
    ["--keep-newer-files"] = { "不覆盖比归档副本更新的文件" },
    ["--overwrite"] = { "解压时覆盖文件（默认）" },
    ["--remove-files"] = { "添加后删除源文件" },
    ["--skip-old-files"] = { "解压时静默跳过已存在文件" },
    ["-O"] = { "解压到标准输出" },
    ["-C"] = { " dir", "切换到指定目录" },
    ["--exclude"] = { " pattern", "排除匹配模式的文件" },
    ["-X"] = { " file", "从文件读取排除模式" },
    ["-T"] = { " file", "从文件读取要处理的名字" },
    ["-p"] = { "保留权限" },
    ["-h"] = { "跟随符号链接" },
    ["--strip-components"] = { " n", "解压时去掉前 n 个路径组件" },
    ["--one-top-level"] = { "解压到单独的子目录（避免散落文件）" },
    ["-S"] = { "高效处理稀疏文件" },
    ["--ignore-failed-read"] = { "遇到不可读文件不报错退出" },
    ["-g"] = { " file", "GNU 增量备份文件" },
    ["-G"] = { "旧版 GNU 增量备份" },
    ["--checkpoint"] = { "定期显示进度" },
    ["-w"] = { "操作前询问确认" },
    ["--wildcards"] = { "模式中使用通配符" },
    ["--no-wildcards"] = { "模式中不使用通配符" },
    ["--ignore-case"] = { "模式匹配忽略大小写" },
    ["--null"] = { "-T 读取 NUL 结尾的名字" },
    ["-W"] = { "写入后验证归档" },
    ["--version"] = { "显示版本" },
    ["--help"] = { "显示帮助" },
})
