-- luacheck: no max line length
--------------------------------------------------------------------------------
-- vim.lua — Vim 编辑器

local file = clink.argmatcher():addarg(clink.filematches)

clink.argmatcher("vim")
:addarg(file)
:addflags({
    "-b",
    "-C",
    "-c"..clink.argmatcher():addarg({fromhistory=true}),
    "-cmd"..clink.argmatcher():addarg({fromhistory=true}),
    "-d",
    "-D",
    "-e",
    "-E",
    "-f",
    "-g",
    "-h",
    "-i"..clink.argmatcher():addarg({fromhistory=true}),
    "-m",
    "-M",
    "-n",
    "-N",
    "-o"..clink.argmatcher():addarg({fromhistory=true}),
    "-O"..clink.argmatcher():addarg({fromhistory=true}),
    "-p"..clink.argmatcher():addarg({fromhistory=true}),
    "-R",
    "-r",
    "-s"..clink.argmatcher():addarg({fromhistory=true}),
    "-S"..clink.argmatcher():addarg(clink.filematches),
    "-u"..clink.argmatcher():addarg(clink.filematches),
    "-V"..clink.argmatcher():addarg({fromhistory=true}),
    "-v",
    "-w"..clink.argmatcher():addarg({fromhistory=true}),
    "-W"..clink.argmatcher():addarg({fromhistory=true}),
    "-x",
    "-X",
    "-y",
    "-Z",
    "--clean",
    "--not-a-term",
    "--version",
})
:adddescriptions({
    ["-b"] = { "二进制模式" },
    ["-C"] = { "兼容模式（兼容 vi）" },
    ["-c"] = { " cmd", "打开文件后执行命令" },
    ["-cmd"] = { " cmd", "读取 .vimrc 前执行命令" },
    ["-d"] = { "diff 模式（比较文件）" },
    ["-D"] = { "调试模式" },
    ["-e"] = { "Ex 模式（单行命令模式）" },
    ["-E"] = { "增强 Ex 模式" },
    ["-f"] = { "前台模式（不 fork，供脚本调用）" },
    ["-g"] = { "GUI 模式" },
    ["-h"] = { "显示帮助" },
    ["-i"] = { " viminfo", "使用指定 viminfo 文件" },
    ["-m"] = { "禁止修改（只读缓冲）" },
    ["-M"] = { "禁止修改（含 'write' 选项）" },
    ["-n"] = { "不使用交换文件" },
    ["-N"] = { "非兼容模式（推荐）" },
    ["-o"] = { " n", "水平分屏打开 n 个文件" },
    ["-O"] = { " n", "垂直分屏打开 n 个文件" },
    ["-p"] = { " n", "以标签页打开 n 个文件" },
    ["-R"] = { "只读模式" },
    ["-r"] = { "恢复上次崩溃的会话" },
    ["-s"] = { " script", "静默模式执行脚本" },
    ["-S"] = { " file", "打开后执行 Vim 脚本文件" },
    ["-u"] = { " vimrc", "使用指定 vimrc（NONE 表示跳过）" },
    ["-V"] = { " verbose", "详细模式（记录启动过程）" },
    ["-v"] = { "Vi 模式（初始兼容）" },
    ["-w"] = { " script", "记录输入的键到脚本" },
    ["-W"] = { " script", "追加记录输入的键到脚本" },
    ["-x"] = { "加密模式" },
    ["-X"] = { "不连接 X 服务器" },
    ["-y"] = { "简易模式" },
    ["-Z"] = { "受限模式" },
    ["--clean"] = { "不使用 vimrc 和插件启动" },
    ["--not-a-term"] = { "不在终端中启动" },
    ["--version"] = { "显示版本信息" },
})
